In [1]:
import numpy as np

In [2]:
# LEVEL 1 BLAS FUNCTIONS TESTS
x = np.array([1+2j, 3+4j, 5+6j])
y = np.array([7-8j, 9-1j, 11+2j])

In [3]:
np.vdot(x,y)

(81-117j)

In [4]:
alpha = 2 + 3j
x = np.array([1+2j, 3+4j])
y = np.array([5-6j, 7-8j])

alpha * x + y

array([1.+1.j, 1.+9.j])

In [9]:
# Level 2 BLAS FUNCTIONS TEST
alpha = 1.1 + 2.2j
beta  = 2.0 + 1.2j
A = np.array([[1.0+1j,3.0+3j,5.0+5j ],
            [2.0+2j,4.0+4j,6.0+6j]])
x = np.array([3.0+3j,2.0+2j, 4.0+4j])
y = np.array([0+1.0j, 1.0+2.0j])

alpha * np.matmul(A, x.transpose()) + beta * y


array([-128.8+65.8j, -167.6+88.8j])

In [8]:
x.transpose()

array([3.+3.j, 6.+6.j])