In [1]:
import numpy as np

In [2]:
# LEVEL 1 BLAS FUNCTIONS TESTS
x = np.array([1+2j, 3+4j, 5+6j])
y = np.array([7-8j, 9-1j, 11+2j])

In [3]:
np.vdot(x,y)

(81-117j)

In [4]:
alpha = 2 + 3j
x = np.array([1+2j, 3+4j])
y = np.array([5-6j, 7-8j])

alpha * x + y

array([1.+1.j, 1.+9.j])

In [9]:
# Level 2 BLAS FUNCTIONS TEST
# ZGEMV
alpha = 1.1 + 2.2j
beta  = 2.0 + 1.2j
A = np.array([[1.0+1j,3.0+3j,5.0+5j ],
            [2.0+2j,4.0+4j,6.0+6j]])
x = np.array([3.0+3j,2.0+2j, 4.0+4j])
y = np.array([0+1.0j, 1.0+2.0j])

alpha * np.matmul(A, x.transpose()) + beta * y


array([-128.8+65.8j, -167.6+88.8j])

In [4]:
# DTRSV
import numpy as np
from scipy.linalg import solve_triangular

A = np.array([[1.0, 0.0, 0.0],[0.5, 1.0, 0.0],[1.0, 0.2, 1.0]])
x = np.array([1.0, 2.0, 3.0])

x = solve_triangular(A, x, lower=True)
x

array([1. , 1.5, 1.7])

In [1]:
# ZTRSV
import numpy as np
from scipy.linalg import solve_triangular

A = np.array([[1.0+1.0j, 0.0, 0.0],[0.5+0.5j, 1.0+2.0j, 0.0],[1.0+2.0j, 0.2+0.3j, 1.0+1.0j]])
x = np.array([1.0+1.0j, 2.0+2.0j, 3.0+3.0j])

x = solve_triangular(A, x, lower=True)
x

array([1.  +0.j  , 0.9 -0.3j , 1.26-0.47j])

In [1]:
# LEVEL 3 BLAS
# DGEMM
import numpy as np
from scipy.linalg import solve_triangular

alpha = 2.5
beta = 1.2
A = np.array([[1,2], [3, 4], [5, 6]], dtype="float64")
B = np.array([[7,8,9,10], [11,12,13,14]], dtype="float64")
C = np.array([[1,2,3,4],[1,2,3,5],[1,2,3,6]], dtype="float64")

alpha * np.matmul(A, B) + beta * C


array([[ 73.7,  82.4,  91.1,  99.8],
       [163.7, 182.4, 201.1, 221. ],
       [253.7, 282.4, 311.1, 342.2]])

In [2]:
# LEVEL 3 BLAS
# DGEMM
import numpy as np
from scipy.linalg import solve_triangular

alpha = 2.5
beta = 1.2
A = np.array([[1+1j,2+2j], [3+3j, 4+1j], [5+5j, 6+1.8j]], dtype="complex128")
B = np.array([[7+14j,8+13j,9+12.1j,10+11.9j], [11+10j,12+9j,13+8.1j,14+7.2j]], dtype="complex128")
C = np.array([[1+1j,2+4j,3+7j,4+11j],[1+2j,2+5j,3+9j,5+12j],[1+3j,2+6j,3+10j,6+13j]], dtype="complex128")

alpha * np.matmul(A, B) + beta * C

array([[-11.3 +158.7j ,   4.9 +162.3j ,  20.35+166.65j,  34.05+173.95j],
       [ 33.7 +287.4j ,  62.4 +283.5j ,  90.1 +282.55j, 113.75+285.65j],
       [ 33.7 +465.6j ,  79.4 +458.7j , 123.4 +455.75j, 161.05+460.35j]])